import dynamic from "next/dynamic";
import Head from "next/head";
import Image from "next/image";
import { host } from "../config"
import styles from '../styles/Home.module.css'
import deals from "./api/deals";
import { useRouter } from 'next/router'
import React, { useState, useEffect } from 'react';
import { TripleMaze } from "react-spinner-animated";
import 'react-spinner-animated/dist/index.css'

const Deal = dynamic(() => import('../components/deal'))

function Layout(){

    const router = useRouter()

    const [data, setData] = useState(null)
    const [isLoading, setLoading] = useState(false)

    useEffect(() => {
        if(!router.isReady) return;
        setLoading(true)
        fetch('/api/deals')
            .then((res) => res.json())
            .then((data) => {
            setData(data.data)
            setLoading(false)
            })
        }, [router.isReady])

    if (isLoading) return <TripleMaze text={"Loading..."} bgColor={"#FFFFFF"} 
    center={true} width={"150px"} height={"150px"}/>
    if (!data) return <div></div>

    return (
        <div >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="w-full flex flex-col block">
                
                {data.sales.map((sale) => (
                    <Deal key="sale.ID" sale={sale} />
                ))}

                
            </main>
            <footer className={styles.footer}>
                <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
                >
                Powered by{' '}
                <span className={styles.logo}>
                    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
                </a>
            </footer>
        </div>
    )
}

export function DealTitle({sale}) {
    return sale.SaleName +" : "+ sale.NumGames + " results"
}

export async function getStaticProps() {

    return {
        props: {
            sales : []
        }
    }
}

export default Layout